### PR TITLE
Double wildcard will match zero segments at the end of a path

### LINKED ISSUE #102: authenticationError is overwritten before the debug log
The debug log should be executed first to allow actual errors to show up.

### PR DESCRIPTION
**Pull request by rockspore**
fix #102

### CODE REVIEW

**Comment by theganyo** [comment]
Why does this have the logging fix in it?

**Comment by rockspore** [comment]
> Why does this have the logging fix in it?

Sorry, forgot to rebase the branch. Done.

**Comment by theganyo** [comment]
Should we have a similar test for extracting the variable? Eg. `/c/{var=**}/x`?

**Comment by rockspore** [comment]
> Should we have a similar test for extracting the variable? Eg. `/c/{var=**}/x`?

Makes a lot of sense! Added those.

**Review by theganyo — APPROVED** [review]

**Pull request merged**
